---
kind: pipeline
metadata:
  app: mcdonald
spec:
  stages:
    dev:
      - build
      - dry-run

  global_variables:
    HELM_NAME: mcdonald
    HELM_NAMESPACE: mcdonald
    HELM_CHART: helm/
    HELM_CHART_VERSION: 0.1.1
    TEST_VAR: "global"

  dev:
    target:
      match:
        name: dev
    build:
      build:
        - type: docker
          name: test/mcdonald-web
          tag: latest
      script:
        - helm repo add ankra-test https://registry.infra.ankra.cloud/chartrepo/test --username 'robot$test' --password Hne33ZWKnRPgTiPV1HREhoVhqHWg0JDD
        - helm repo list
        - helm dependency update helm/
        - helm package helm/ --version $HELM_CHART_VERSION
        - helm cm-push helm/mcdonald-web-$HELM_CHART_VERSION.tgz ankra-test
    dry-run:
      script:
        - helm -n $HELM_NAMESPACE list
        - helm upgrade --install -n $HELM_NAMESPACE $HELM_NAME $HELM_CHART --create-namespace --dry-run
